title: Jorge Rodríguez Mora
author: jorgermasir
email: jorgemovil2112@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My journey in GitHub begins.

# social links
twitter_username: @JorgeRM92
github_username:  jorgermasir

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimas
